language: none
services:
 - docker
 
env:
 - REGISTRY_EMAIL=jacob.meloche\@aquasec.com
 - REGISTRY_PW=Alexander1

before_install:
 - docker login registry.aquasec.com -u jacob.meloche@aquasec.com -p Alexander1
 - docker pull registry.aquasec.com/scanner:5.3
 - docker pull dit4c/gotty:latest
 - docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/tmp registry.aquasec.com/scanner:5.3 scan --host http://51.105.210.25:8080/ -U administrator -P @password --local dit4c/gotty:latest --layer-vulnerabilities --no-verify
