before_install:
 - docker login registry.aquasec.com -u jacob.meloche@aquasec.com -p Alexander1
 - docker pull registry.aquasec.com/scanner:5.3
 - docker pull dit4c/gotty:latest
 - docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/tmp registry.aquasec.com/scanner:5.3 scan --host https://1xor8bqaw-d-us-e1-s-console.aese.aquasec.com/ -U administrator -P password --local dit4c/gotty:latest --layer-vulnerabilities --no-verify
