before_install:
 - docker login registry.aquasec.com -u $AQUA_USER -p $AQUA_PASSWORD
 - docker pull registry.aquasec.com/scanner:5.3
 - docker pull dit4c/gotty:latest
 - docker run -e BUILD_NUMBER=$TRAVIS_BUILD_NUMBER -e BUILD_URL=$TRAVIS_BUILD_WEB_URL -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/tmp registry.aquasec.com/scanner:5.3 scan --host http://aquasec-demo1828-vm0.eastus.cloudapp.azure.com/ -U administrator -P P@ssword01 --local dit4c/gotty:latest --layer-vulnerabilities --no-verify
