before_install:
 - docker login registry.aquasec.com -u $AQUA_USER -p $AQUA_PASSWORD
 - docker pull registry.aquasec.com/scanner:5.3
 - docker pull dit4c/gotty:latest
 - docker run -e BUILD_NUMBER=$TRAVIS_BUILD_NUMBER \
  -e BUILD_JOB_NAME=$TRAVIS_BUILD_ID \ 
  -it --rm -v /var/run/docker.sock:/var/run/docker.sock \ 
  -v /tmp:/tmp registry.aquasec.com/scanner:5.3 scan \ 
  --host https://1xor8bqaw-d-us-e1-s-console.aese.aquasec.com/ \ 
  -U jmeloche -P Aqu@sec5 --local dit4c/gotty:latest --layer-vulnerabilities --no-verify
